# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='datadata',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
