# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20160618_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='importance',
            field=models.CharField(default='important', max_length=100),
        ),
    ]
