# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_changed_my_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
