# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_changed_my_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='picture',
            field=models.FileField(upload_to=b''),
        ),
    ]
